[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
  "contracts/=contracts/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]


[profile.default.rpc_endpoints]
sepolia = "https://go.getblock.io/956b49eb14ae42a18fa8801d7f498b9f"

[profile.default.env]
PRIVATE_KEY = "${PRIVATE_KEY}"
